os: linux
language: java
jdk:
- oraclejdk11
- openjdk8
- openjdk11
deploy:
  - provider: script
    script: ./deploy-gh-pages.sh
    on:
      branch: master
      jdk: openjdk11
  - provider: script
    script: ./deploy-bintray.sh
    on:
      tags: true
      jdk: openjdk11

env:
  global:
  # GitHub
  - secure: nOzpcW4Uw+QBTJ50mDmlzBQLLZsoLzIKF7ql2HdR3Ww5f9D/NycLF6iqhuH68YFOSu1kSfLJLehVS3SaQ0y3blZxNgP/JNOviJg15rvSvlZLWZkTLXF5npEX5ObeULP8MUxBsw6iNF8GMfNqGob+hun4K5eIORHVlv0zU3zIsffUWsDsB34dXuRDbS4b2aA0jsrpq4qMHK13Xw89fzZKpgvdmzQLeJkTQY4DOrjdpNu35IyCjopP9Ssvir0PqhQZBcolkbSltBo82X7GCviunSYLqwSy4mchYzs9i2MYMzOlHAfwIbWx1e43fDTouJZZuSU/rzLt1g40+qqyDwuV7bhzA7NTQoaEWcz6YUz58ajLZlMYialZq3R3NXVKuRbjLTyxDxaf2IcGcI1yUsKoYliJgMQYC7byFuji8ykfnVOfTCQhR32nT0t6IPZKVhxL7BoG5EDM263qGdgwpTTtq1L5DWvYAd4EEKbalAp0d+jYDIVo890EIcxru7/5uoVBoy+y4Y/ZS7x7hAiG62le5OfaY9yb2cZfeNUnrf6n8Stz9gJHLxOhBa77exXsSxx6SxUXG73m3PALV6iQv92nWG+q8zjdQV3XOKQUTjox9S52XmbNWc4cNWHQGq15sIjvW4yMSYHu7IxMxRlKpLggL3BQ2/2pvHODRBBwXQvGo4g=
  # Bintray
  - secure: LKYpgp/2LBUP3i+FLBcxqmQG2BHyabcZVhoa21k1iyFeKVHnRFej8AFX6+3CrSKSLaU89GpwthdGKu30F1kQAtNtwVdpRGVahk25gSsOU4cI1xMyrYtTtpZJgOBhR3Cpz1U/sif9wJijMzRwJ1+111Nt4HZBM9Yk2ofQcFGmH+2v10W31FS1OY8/Wc6HT46Lb08ZyrR87Sc3es6GDjMEAKZ/OYRRA5kCvIvgbDZMVns+nQD5j0ae8GRIaAs6y0+pxZt96HN1ES6IhQjho0xMgEfCQAxBzA5ISTtEVTY/xFhZ5rntaqnorC9PN+4PzJgU01z1GFoUgbJ/w6py13NACAS9zQpE7z873PGe/ipVMbb9VVbbOztfMw6Me+pYeFE35c497q1AS7fUoJ4rYOYm0MwIcRu/shlA722KtWSyXQlor1JYWgfp90sDWMsQoTxrKjIiwZVUpVLgNKG7aaouFiu1nXqXuULDJxkZSvf4i2FfQlotSXj2RBNi540IUr4piNJhZxTMiLVtUt4y8yeayyZ6WMTv64ReB4Z/nLZbbpdNkRPRMzZbNZqVQ+j8vpnyVIkBnU7/fKk/241PplRIevjR6HubUcC5SaOS3c4zXlxrCFQjKnzeDbkvDViquDwhCRCNMWinQDX3LEPWYeKVNjlZ0APx0lh9vYmXGZHIXWY=
